import scraper_flashbay
import scraper_flashbay_cleaning
import scraper_steelseries
import scraper_steelseries_cleaning
import scraper_asda
import scraper_asda_cleaning
import scraper_quicken
import scraper_quicken_cleaning

import initial_data_cleaning_trustpilot.ipynb
import initial_feature_processing.ipynb
import basic_text_statistics_trustpilot.ipynb
import exploratory_data_analysis_trustpilot.ipynb


